### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by trevynmace** [buzz/volctl#41]
I'm really excited to get this working as it's just the tool I'm looking for, without having to write my own.

I ran into some issues during install, specifically with dependencies I didn't know I needed, such as:
`python-dev`
`libcairo2-dev`
I also had to specify a version of pycairo in the setup.py file, because the latest pycairo doesn't support Python2 anymore.
I used version 1.18.1 of pycairo.

Now on install, I get these errors:

```
running install
running bdist_egg
running egg_info
writing requirements to volctl.egg-info/requires.txt
writing volctl.egg-info/PKG-INFO
writing top-level names to volctl.egg-info/top_level.txt
writing dependency_links to volctl.egg-info/dependency_links.txt
writing entry points to volctl.egg-info/entry_points.txt
reading manifest file 'volctl.egg-info/SOURCES.txt'
writing manifest file 'volctl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/status_icon.py -> build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/__init__.py -> build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/slider_win.py -> build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/xwrappers.py -> build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/app.py -> build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/__main__.py -> build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/osd.py -> build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/pulsemgr.py -> build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/prefs.py -> build/bdist.linux-x86_64/egg/volctl
copying build/lib.linux-x86_64-2.7/volctl/meta.py -> build/bdist.linux-x86_64/egg/volctl
byte-compiling build/bdist.linux-x86_64/egg/volctl/status_icon.py to status_icon.pyc
  File "build/bdist.linux-x86_64/egg/volctl/status_icon.py", line 76
    getattr(self, f"_create_{self._current_impl}")()
                                                ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/volctl/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/volctl/slider_win.py to slider_win.pyc
  File "build/bdist.linux-x86_64/egg/volctl/slider_win.py", line 218
    name = f"<b>{proplist['application.name']}</b>: {proplist['media.name']}"
                                                                            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/volctl/xwrappers.py to xwrappers.pyc
byte-compiling build/bdist.linux-x86_64/egg/volctl/app.py to app.pyc
byte-compiling build/bdist.linux-x86_64/egg/volctl/__main__.py to __main__.pyc
byte-compiling build/bdist.linux-x86_64/egg/volctl/osd.py to osd.pyc
byte-compiling build/bdist.linux-x86_64/egg/volctl/pulsemgr.py to pulsemgr.pyc
  File "build/bdist.linux-x86_64/egg/volctl/pulsemgr.py", line 176
    obj_list = getattr(pulse, f"{fac}_list")()
                                          ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/volctl/prefs.py to prefs.pyc
byte-compiling build/bdist.linux-x86_64/egg/volctl/meta.py to meta.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/share
creating build/bdist.linux-x86_64/egg/share/applications
copying data/volctl.desktop -> build/bdist.linux-x86_64/egg/share/applications
creating build/bdist.linux-x86_64/egg/share/glib-2.0
creating build/bdist.linux-x86_64/egg/share/glib-2.0/schemas
copying data/apps.volctl.gschema.xml -> build/bdist.linux-x86_64/egg/share/glib-2.0/schemas
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying volctl.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying volctl.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying volctl.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying volctl.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying volctl.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying volctl.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/volctl-0.8.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing volctl-0.8.2-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/volctl-0.8.2-py2.7.egg
Copying volctl-0.8.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
volctl 0.8.2 is already the active version in easy-install.pth
Installing volctl script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/volctl-0.8.2-py2.7.egg
Processing dependencies for volctl==0.8.2
Searching for pycairo==1.18.1
Best match: pycairo 1.18.1
Processing pycairo-1.18.1-py2.7-linux-x86_64.egg
pycairo 1.18.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pycairo-1.18.1-py2.7-linux-x86_64.egg
Searching for pulsectl==21.3.4
Best match: pulsectl 21.3.4
Processing pulsectl-21.3.4-py2.7.egg
pulsectl 21.3.4 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pulsectl-21.3.4-py2.7.egg
Searching for click==7.1.1
Best match: click 7.1.1
Processing click-7.1.1-py2.7.egg
click 7.1.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/click-7.1.1-py2.7.egg
Searching for PyYAML==5.4.1
Best match: PyYAML 5.4.1
Processing PyYAML-5.4.1-py2.7-linux-x86_64.egg
PyYAML 5.4.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/PyYAML-5.4.1-py2.7-linux-x86_64.egg
Searching for PyGObject==3.36.0
Best match: PyGObject 3.36.0
Adding PyGObject 3.36.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for setuptools==44.0.0
Best match: setuptools 44.0.0
Adding setuptools 44.0.0 to easy-install.pth file
Installing easy_install script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for volctl==0.8.2
```

I didn't actually notice the errors the first time I tried installing after getting dependencies set up correctly, so then when I try to run volctl, I get this error, similar to the syntax errors on install:

```
Traceback (most recent call last):
  File "/usr/local/bin/volctl", line 11, in <module>
    load_entry_point('volctl==0.8.2', 'gui_scripts', 'volctl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/volctl/__main__.py", line 12, in <module>
  File "build/bdist.linux-x86_64/egg/volctl/app.py", line 15, in <module>
  File "/usr/local/lib/python2.7/dist-packages/volctl-0.8.2-py2.7.egg/volctl/status_icon.py", line 76
    getattr(self, f"_create_{self._current_impl}")()
                                                ^
SyntaxError: invalid syntax
```

Would love any help!
Running ubuntu 20.04
Thanks! :)

**Comment by Narrat** [comment]
Why are you trying to install volctl with python2?
Should work perfectly fine with python3

**Comment by trevynmace** [comment]
Thanks for the quick response!!
You're absolutely right lol. Not sure why I was using python2 initially. Okay it installs without error using Python3, however now when I try to run the volctl command, I get a new error:
```
Traceback (most recent call last):
  File "/usr/local/bin/volctl", line 11, in <module>
    load_entry_point('volctl==0.8.2', 'gui_scripts', 'volctl')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/volctl-0.8.2-py3.8.egg/volctl/__main__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/volctl-0.8.2-py3.8.egg/volctl/app.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/volctl-0.8.2-py3.8.egg/volctl/status_icon.py", line 6, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace StatusNotifier not available
```

I know switching to StatusNotifier was a recent change. Is there an additional dependency for that project? Although it seems like it may simply not exist.

**Comment by buzz** [comment]
You need to have [statusnotifier](https://github.com/jjk-jacky/statusnotifier) installed. Or just use the stable release version.

**Comment by trevynmace** [comment]
Hey thanks for the heads up! I tried to compile statusnotifier from source and ran into issues as well... and there aren't any build instructions on that project.
Can you point me to where the stable release version of voltctl (volctl?) is? Or how would I go about installing that?
Thanks!

**Comment by buzz** [comment]
Download the latest version from the [release page](https://github.com/buzz/volctl/releases), unzip the file and follow [install instructions](https://buzz.github.io/volctl/).

**Comment by trevynmace** [comment]
Okay, successfully installed using latest stable.
Now if I run the volctl command from terminal, I get `PulseAudio: Connection ready` with no further output unless I kill the command, which is expected, however there's no status icon on the top menu bar (the only menu bar).
Is there somewhere I should look for logging to see why the icon isn't being created correctly? Or am I missing something else?

**Comment by trevynmace** [comment]
Oddly, the OSD is displaying correctly for the master output volume while volctl is running, just no tray icon

**Comment by buzz** [comment]
For the status icon to work, your Desktop Environment needs to support the XEmbed specification. The master branch additionally supports StatusNotifier (SNI).

**Comment by buzz** [comment]
Closed for inactivity
