### ISSUE TITLE
Volctl not launching

### ISSUE THREAD

**Issue by Strix007** [buzz/volctl#78]
Whenever I try to launch volctl, I get this error

```
Traceback (most recent call last):
  File "/usr/bin/volctl", line 33, in <module>
    sys.exit(load_entry_point('volctl==0.9.4', 'gui_scripts', 'volctl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/volctl/__main__.py", line 20, in main
    app = VolctlApp()
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/volctl/app.py", line 53, in __init__
    self.pulsemgr = PulseManager(self)
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/volctl/pulsemgr.py", line 83, in __init__
    format=c.PA_SAMPLE_FLOAT32NE, rate=25, channels=1
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pulsectl._pulsectl' has no attribute 'PA_SAMPLE_FLOAT32NE'. Did you mean: 'PA_SAMPLE_FLOAT32BE'?
```

**Comment by Strix007** [comment]
Thanks, it worked though I had to reinstall it through pip.
