### ISSUE TITLE
Volctl Fails to Launch at System Startup

### ISSUE THREAD

**Issue by raven2cz** [buzz/volctl#86]
I primarily use AwesomeWM. I have a script that repeatedly checks if Volctl has been launched and attempts to start it three times in succession. Despite this, it often fails to launch. Specifically, it might successfully launch only 2 out of 5 times. The success rate seems dependent on Pipewire or some other services, but I cannot pinpoint the exact cause of the issue.

I have been encountering this problem for at least six months; previously, I had no such issues. I would appreciate any assistance to resolve this, as I'm puzzled about what could be causing these launch failures. When I manually start it after the system has booted up, it launches immediately without any issues.

**Comment by buzz** [comment]
Sounds like some race condition. volctl depends on PulseAudio (or the pipewire-pulse service) and the system tray/dbus to be available, depending on the systray protocol you are using.

It would be helpful if you could provide a console log of volctl to be sure what the underlying issue is.

Is this different from https://github.com/buzz/volctl/issues/81#issuecomment-1695075292? If no, then we should continue the discussion in the old issue to keep things tidy.

**Comment by freezboltz** [comment]
@buzz here is the console output
OS: EndeavourOS Linux x86_64
Kernel: 6.12.6-arch1-1
WM: awesome

```
File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 407, in from_name
    return next(iter(cls.discover(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/volctl", line 33, in <module>
    sys.exit(load_entry_point('volctl==0.9.4', 'gui_scripts', 'volctl')())
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/volctl", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 960, in distribution
    return Distribution.from_name(distribution_name)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 409, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for volctl

[1]  + exit 1     volctl
```
```

**Comment by buzz** [comment]
> @buzz here is the console output

This doesn't seem to be related to this issue at all. In your case, reinstalling volctl should help. Python was upgraded to 3.13, and your volctl installation is for an older version, would be my guess.
